### ISSUE TITLE
Torch.nn.Conv2D fails in aot

### ISSUE THREAD

**Issue by zjgarvey** [nod-ai/SHARK-Turbine#111]
Here is a minimal-ish reproducer and the corresponding error message.

Tested on both torch 2.1 and 2.2.

```
import torch
import torch.nn as nn
from shark_turbine.aot import *
from iree.compiler.ir import Context

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 8, 5)

    def forward(self, x):
        return self.conv1(x)

model = Model()

class ConvModule(CompiledModule):
    #this one is trying to pass the pixel_value tensor as an Abstract Tensor?
    params = export_parameters(model, initialize =False) #         is this necessary? 

    def forward(self, x = AbstractTensor(1, 3, 224, 224, dtype=torch.float32) ):
        fwd = model.forward(x)
        return fwd

inst2 = ConvModule(context=Context(), import_to="IMPORT")
```

```
Traceback (most recent call last):
  File "C:\Users\zjgar\code\SHARK-Turbine\tests\aot\NotImpltest.py", line 27, in <module>
    inst2 = ConvModule(context=Context(), import_to="IMPORT")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zjgar\code\SHARK-Turbine\python\shark_turbine\aot\compiled_module.py", line 534, in __new__
    do_export(proc_def)
  File "C:\Users\zjgar\code\SHARK-Turbine\python\shark_turbine\aot\compiled_module.py", line 531, in do_export
    trace.trace_py_func(invoke_with_self)
  File "C:\Users\zjgar\code\SHARK-Turbine\python\shark_turbine\aot\support\procedural\tracer.py", line 120, in trace_py_func
    return_py_value = _unproxy(py_f(*self.proxy_posargs, **self.proxy_kwargs))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zjgar\code\SHARK-Turbine\python\shark_turbine\aot\compiled_module.py", line 512, in invoke_with_self
    return proc_def.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zjgar\code\SHARK-Turbine\tests\aot\NotImpltest.py", line 22, in forward
    fwd = model.forward(x)
          ^^^^^^^^^^^^^^^^
  File "C:\Users\zjgar\code\SHARK-Turbine\tests\aot\NotImpltest.py", line 13, in forward
    return self.conv1(x)
           ^^^^^^^^^^^^^
  File "C:\Users\zjgar\code\SHARK-Turbine\examples\resnet-18\resnet.venv\Lib\site-packages\torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zjgar\code\SHARK-Turbine\examples\resnet-18\resnet.venv\Lib\site-packages\torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zjgar\code\SHARK-Turbine\examples\resnet-18\resnet.venv\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zjgar\code\SHARK-Turbine\examples\resnet-18\resnet.venv\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Multiple dispatch failed for 'torch.conv2d'; all __torch_function__ handlers returned NotImplemented:

  - tensor subclass <class 'shark_turbine.aot.support.procedural.primitives.IrImmediateTensor'>

```

**Comment by zjgarvey** [comment]
Solvable by wrapping forward in jittable. See code below:

```
import torch
import torch.nn as nn
from shark_turbine.aot import *
from iree.compiler.ir import Context

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 8, 5)

    def forward(self, x):
        return self.conv1(x)

model = Model()

class ConvModule(CompiledModule):
    #this one is trying to pass the pixel_value tensor as an Abstract Tensor?
    params = export_parameters(model, initialize =False) #         is this necessary? 

    def forward(self, x = AbstractTensor(1, 3, 224, 224, dtype=torch.float32) ):
        fwd = jittable(model.forward)(x)
        #label = logits0.argmax(-1).item()
        #str_output = model.config.id2label[predicted_label0] 
        return fwd

inst2 = ConvModule(context=Context(), import_to="IMPORT")
module_str2 = str(CompiledModule.get_mlir_module(inst2))
print(module_str2)
```
