### ISSUE TITLE
simple export mlp breaks on windows

### ISSUE THREAD

**Issue by dan-garvey** [nod-ai/SHARK-Turbine#112]
```
======================================================================
ERROR: testMLPExportSimple (__main__.ModelTest.testMLPExportSimple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\work\SHARK-Turbine\examples\aot_mlp\mlp_export_simple.py", line 57, in testMLPExportSimple
    infer()
  File "D:\work\SHARK-Turbine\examples\aot_mlp\mlp_export_simple.py", line 47, in infer
    rt.VmModule.wrap_buffer(config.vm_instance, compiled_binary.map_memory()),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: VmModule.from_aligned_memory received an unaligned buffer. Got 0x000001C3A89A14A0, expected alignment 64

----------------------------------------------------------------------
Ran 1 test in 0.001s
```

**Comment by stellaraccident** [comment]
This was fixed by an iree patch a week and a half ago. Unfortunately, it was also the same patch that incidentally broke the releases due a few days, so we just caught up this evening. Should be fixed at head now.
