### ISSUE TITLE
adaptive_max_pool2d is not supported

### ISSUE THREAD

**Issue by JBloodless** [nod-ai/SHARK-Turbine#116]
Hi again. Found another unsupported op - `adaptive_max_pool2d`

Repro:

```
import shark_turbine.aot as aot
import torch
import torch.nn as nn
import torch.nn.functional as F


class AdaptCNN(nn.Module):
    def __init__(self,
                 input_channels=1,
                 c_out_1=16,
                 kernel_size=(3, 3),
                 pool_1=(24,7)
                 ):
        super().__init__()

        self.input_channels = input_channels
        self.c_out_1 = c_out_1
        self.kernel_size = kernel_size
        self.pool_1=pool_1

        self.cnn_pad = (1, 1)

        self.conv1 = nn.Conv2d(
            self.input_channels,
            self.c_out_1,
            self.kernel_size,
            padding=self.cnn_pad)

        self.bn1 = nn.BatchNorm2d(self.conv1.out_channels)

    def forward(self, x):
        x = self.bn1(self.conv1(x))
        x = F.adaptive_max_pool2d(x, output_size=self.pool_1)
        return x


x = torch.zeros((63, 1, 48, 15), dtype=torch.float)

model = AdaptCNN()
model.eval()

export_output = aot.export(model, x)
binary = export_output.compile(save_to=None)
```

It throws

```
Traceback (most recent call last):
  File "/Users/i.beskrovnyy/tts/NISQA-s/repro_adaptmaxpool.py", line 42, in <module>
    export_output = aot.export(model, x)
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/exporter.py", line 198, in export
    cm = Exported(context=context, import_to="import")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/compiled_module.py", line 534, in __new__
    do_export(proc_def)
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/compiled_module.py", line 531, in do_export
    trace.trace_py_func(invoke_with_self)
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/support/procedural/tracer.py", line 120, in trace_py_func
    return_py_value = _unproxy(py_f(*self.proxy_posargs, **self.proxy_kwargs))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/compiled_module.py", line 512, in invoke_with_self
    return proc_def.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/exporter.py", line 182, in main
    return jittable(mdl.forward)(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/support/procedural/base.py", line 137, in __call__
    return current_ir_trace().handle_call(self, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/support/procedural/tracer.py", line 136, in handle_call
    return target.resolve_call(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/builtins/jittable.py", line 239, in resolve_call
    fx_importer.import_stateless_graph(gm.graph, func_name=self.function_name)
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/dynamo/importer.py", line 265, in import_stateless_graph
    node_importer.import_nodes(g.nodes)
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/dynamo/importer.py", line 496, in import_nodes
    self._import_torch_op_overload(loc, node, target)
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/dynamo/importer.py", line 633, in _import_torch_op_overload
    raise NotImplementedError(
NotImplementedError: Unimplemented torch op in the IREE compiler: 'torch.aten.adaptive_max_pool2d' (either implement this op/variant or configure the compiler to allow unknown operations and fallback to PyTorch).
```

If I try to implement workaround using basic `max_pool2d`:

```
def adaptive_max_pool2d(input, output_size):
    # Get the size of the input tensor
    h, w = input.size(2), input.size(3)

    # Calculate the kernel size and stride for each region
    stride_h = h // output_size[0]
    stride_w = w // output_size[1]
    kernel_h = h - (output_size[0] - 1) * stride_h
    kernel_w = w - (output_size[1] - 1) * stride_w

    # Apply max_pool2d with the calculated kernel size and stride
    output = F.max_pool2d(input, kernel_size=(kernel_h, kernel_w), stride=(stride_h, stride_w))

    return output
```

it throws new error:

```
Traceback (most recent call last):
  File "/Users/i.beskrovnyy/tts/NISQA-s/repro_adaptmaxpool.py", line 57, in <module>
    export_output = aot.export(model, x)
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/exporter.py", line 198, in export
    cm = Exported(context=context, import_to="import")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/compiled_module.py", line 534, in __new__
    do_export(proc_def)
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/compiled_module.py", line 531, in do_export
    trace.trace_py_func(invoke_with_self)
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/support/procedural/tracer.py", line 120, in trace_py_func
    return_py_value = _unproxy(py_f(*self.proxy_posargs, **self.proxy_kwargs))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/compiled_module.py", line 512, in invoke_with_self
    return proc_def.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/exporter.py", line 182, in main
    return jittable(mdl.forward)(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/support/procedural/base.py", line 137, in __call__
    return current_ir_trace().handle_call(self, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/support/procedural/tracer.py", line 136, in handle_call
    return target.resolve_call(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/builtins/jittable.py", line 207, in resolve_call
    transformed_f = functorch_functionalize(transformed_f, *flat_pytorch_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/passes/functorch.py", line 47, in functorch_functionalize
    new_gm = proxy_tensor.make_fx(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 841, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 406, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 461, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/fx/_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
                     ^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 497, in wrapped
    out = f(*tensors)
          ^^^^^^^^^^^
  File "<string>", line 1, in <lambda>
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/passes/functorch.py", line 65, in wrapped
    out = function(*args_functional)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/builtins/jittable.py", line 202, in flat_wrapped_f
    return self.wrapped_f(*pytorch_args, **pytorch_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/tts/NISQA-s/repro_adaptmaxpool.py", line 48, in forward
    x = adaptive_max_pool2d(x, output_size=self.pool_1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/tts/NISQA-s/repro_adaptmaxpool.py", line 18, in adaptive_max_pool2d
    output = F.max_pool2d(input, kernel_size=(kernel_h, kernel_w), stride=(stride_h, stride_w))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/_jit_internal.py", line 488, in fn
    return if_false(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/nn/functional.py", line 791, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: max_pool2d(): argument 'kernel_size' (position 2) must be tuple of ints, but found element of type SymInt at pos 1
```

which is kinda obvious since I create a bunch of constants in my functions, which become SymInts. 

More interesting thing happens if I try to get rid of F.max_pool2d completely, like

```
def adaptive_max_pool2d(input, output_size):
    h, w = input.size(2), input.size(3)
    batch_size, channels = input.size(0), input.size(1)
    stride_h = h // output_size[0]
    stride_w = w // output_size[1]
    kernel_h = h - (output_size[0] - 1) * stride_h
    kernel_w = w - (output_size[1] - 1) * stride_w
    output = input.new_empty((batch_size, channels, output_size[0], output_size[1]))
    for b in range(batch_size):
        for c in range(channels):
            for i in range(0, h - kernel_h + 1, stride_h):  # Adjusted range for height
                for j in range(0, w - kernel_w + 1, stride_w):  # Adjusted range for width
                    region = input[b, c, i:i + kernel_h, j:j + kernel_w]
                    output[b, c, i // stride_h, j // stride_w] = region.max()
    return output
```

This variation hangs up converter completely (it just don't respond and I can only kill the process). If I try to keep loops to minimum:

```
def adaptive_max_pool2d(input, output_size):
    # Get the size of the input tensor
    h, w = input.size(2), input.size(3)

    # Calculate the kernel size and stride for each region
    stride_h = h // output_size[0]
    stride_w = w // output_size[1]
    kernel_h = h - (output_size[0] - 1) * stride_h
    kernel_w = w - (output_size[1] - 1) * stride_w

    # Unfold the input tensor to extract sliding windows
    unfolded = input.unfold(2, kernel_h, stride_h).unfold(3, kernel_w, stride_w)

    # Reshape to isolate each window and then take the max
    unfolded = unfolded.contiguous().view(*unfolded.size()[:4], -1)
    output = unfolded.max(-1)[0]

    return output
```

then it breaks with

```
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/dynamo/importer.py", line 633, in _import_torch_op_overload
    raise NotImplementedError(
NotImplementedError: Unimplemented torch op in the IREE compiler: 'torch.aten.unfold' (either implement this op/variant or configure the compiler to allow unknown operations and fallback to PyTorch).
```

Is there any workaround that I'm missing?

**Comment by dan-garvey** [comment]
I'm sure unfold is just a variation on some other kind of tensor manipulation, if you use ops that are already supported you can workaround the absence of a torch lowering. @zjgarvey you could take a stab at doing the decomposition for unfold in torch-mlir if you want

**Comment by zjgarvey** [comment]
You may be able to make the input.unfold(...) example work by doing torch.unfold_copy(input, ...), but I found that this still causes an error:

```
 error: 'tensor.cast' op operand type 'tensor<?xui8>' and result type 'tensor<0xi8>' are cast incompatible
Traceback (most recent call last):
  File "C:\Users\zjgar\code\SHARK-Turbine\tests\opssupp\case116_1.py", line 43, in <module>
    binary = export_output.compile(save_to=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zjgar\code\SHARK-Turbine\python\shark_turbine\aot\exporter.py", line 138, in compile
    raise RuntimeError("Compilation failed: See diagnostics")
RuntimeError: Compilation failed: See diagnostics
```

The same error occurs even if you take your original example and simply comment out the line "x = F.adaptive_max_pool2d(x, output_size=self.pool_1)" in your definition of forward, so it doesn't have anything to do with the adaptive_max_pool2d implementation. The error seems to come from applying BatchNorm2d, but I'm not sure what is going on quite yet.

**Comment by JBloodless** [comment]
Yeah, in #110 I asked about BatchNorm2d, still seems to not work. I'll leave this issue open for a while, maybe there will be native support for `adaptive_max_pool2d` in the future.

**Comment by dan-garvey** [comment]
#159 is the tracking issue for adaptive_max_pool2d

**Comment by JBloodless** [comment]
> You may be able to make the input.unfold(...) example work by doing torch.unfold_copy(input, ...), but I found that this still causes an error:
> 
> ```
>  error: 'tensor.cast' op operand type 'tensor<?xui8>' and result type 'tensor<0xi8>' are cast incompatible
> Traceback (most recent call last):
>   File "C:\Users\zjgar\code\SHARK-Turbine\tests\opssupp\case116_1.py", line 43, in <module>
>     binary = export_output.compile(save_to=None)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\zjgar\code\SHARK-Turbine\python\shark_turbine\aot\exporter.py", line 138, in compile
>     raise RuntimeError("Compilation failed: See diagnostics")
> RuntimeError: Compilation failed: See diagnostics
> ```
> 
> The same error occurs even if you take your original example and simply comment out the line "x = F.adaptive_max_pool2d(x, output_size=self.pool_1)" in your definition of forward, so it doesn't have anything to do with the adaptive_max_pool2d implementation. The error seems to come from applying BatchNorm2d, but I'm not sure what is going on quite yet.

On `iree-compiler-20231130.724` and `iree-runtime==20231130.724`, where BatchNorm seems to be fixed (see #110), this repro (with `torch.unfold_copy` version of `adaptive_max_pool2d`) still gives 

```
loc("<eval_with_key>.0 from /Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py:509 in wrapped":6:0): error: failed to legalize operation 'torch.constant.int'
Traceback (most recent call last):
  File "/Users/i.beskrovnyy/tts/NISQA-s/repros/repro_adaptmaxpool.py", line 125, in <module>
    binary = export_output.compile(save_to=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/SHARK-Turbine/python/shark_turbine/aot/exporter.py", line 138, in compile
    raise RuntimeError("Compilation failed: See diagnostics")
RuntimeError: Compilation failed: See diagnostics
```

even if I remove everything except `adaptive_max_pool2d` from repro.

**Comment by zjgarvey** [comment]
Actually, I'm not sure if unfold_copy has a decomposition either, now that I'm more familiar with the torch-mlir repository. It appears to be in the [ods gen](https://github.com/llvm/torch-mlir/blob/main/projects/pt1/python/torch_mlir/jit_ir_importer/build_tools/torch_ods_gen.py#L672), but I'm not seeing any decomposition or conversion for it. 

As a side note, the unfold version of adaptive_max_pool2d, which you are implementing, is technically different than the pytorch cpu implementation of that function, which follows the start_index and end_index pattern in [AdaptivePooling.h](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/AdaptivePooling.h#L21) (where a is the output index, b is the output size, and c is the input size). I'm not sure if that is important to you, but I figured I would point it out.

**Comment by JBloodless** [comment]
Long time no see :) Is there any news on this op?

**Comment by zjgarvey** [comment]
Hi! Yes, I'm almost done writing a lowering of that op (without indices).
I'll put a link here to the PR when it is posted later this week.

-Zach

**Comment by zjgarvey** [comment]
I'm running into some (hopefully minor) issues, so a PR for this op might be slightly delayed. I'll keep this thread updated.

**Comment by zjgarvey** [comment]
@JBloodless I worked out the issue I was encountering. Here's the corresponding torch-mlir PR: https://github.com/llvm/torch-mlir/pull/2779

**Comment by JBloodless** [comment]
> @JBloodless I worked out the issue I was encountering. Here's the corresponding torch-mlir PR: [llvm/torch-mlir#2779](https://github.com/llvm/torch-mlir/pull/2779)

```
torch-mlir	20240127.1096	
shark-turbine	0.9.1.dev3	
torch	2.3.0.dev20240122	
iree-compiler-20231218.742 
iree-runtime-20231218.742 
shark-turbine-0.9.3
```

On this combination of versions I'm still getting 

```
loc("<eval_with_key>.0 from /Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py:650 in wrapped":5:0): error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
Traceback (most recent call last):
  File "/Users/i.beskrovnyy/tts/NISQA-s/repros/repro_adaptmaxpool.py", line 115, in <module>
    binary = export_output.compile(save_to=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/shark_turbine/aot/exporter.py", line 138, in compile
    raise RuntimeError("Compilation failed: See diagnostics")
RuntimeError: Compilation failed: See diagnostics
```

with `torch.nn.functional.adaptive_max_pool2d`. With my custom implementation (`unfold_copy` one) first line of error is 

```
loc("<eval_with_key>.0 from /Users/i.beskrovnyy/anaconda3/envs/mlir/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py:650 in wrapped":6:0): error: failed to legalize operation 'torch.constant.int'
```

**Comment by zjgarvey** [comment]
@JBloodless Thanks for testing that out. Let me take a look and see if I can debug what's going on. 

To verify, the first error occurs when running the original version of your code, correct?

I believe unfold and unfold_copy are still unsupported, so I wouldn't expect those to work.

**Comment by JBloodless** [comment]
> @JBloodless Thanks for testing that out. Let me take a look and see if I can debug what's going on.
> 
> To verify, the first error occurs when running the original version of your code, correct?
> 
> I believe unfold and unfold_copy are still unsupported, so I wouldn't expect those to work.

Yes, first one is with usual torch.nn.functional.adaptive_max_pool2d

**Comment by zjgarvey** [comment]
@JBloodless It looks like torch.aten.adaptive_max_pool2d is getting imported as a torch.operator, which means it doesn't recognize it as an op with an existing decomposition (see [fx_importer.py](https://github.com/nod-ai/SHARK-Turbine/blob/main/python/shark_turbine/importers/fx_importer.py#L720)).

My understanding is that shark-turbine is getting the torch-mlir decompositions through iree, so if iree isn't up to date, it still won't have access to the newer decompositions. I also believe that the torch-mlir version is pinned in iree, so we may need to bump the version there. @dan-garvey can you check this out?

**Comment by JBloodless** [comment]
@zjgarvey did anything change since then?

**Comment by zjgarvey** [comment]
> @zjgarvey did anything change since then?

The changes are almost certainly adopted into IREE by now. I'll try running the original script today and see if it works. Thanks for checking back in.

**Comment by zjgarvey** [comment]
Hi, as long as numpy < version 2.0 is being used (see [this issue](https://github.com/nod-ai/SHARK-Turbine/issues/530)) , it looks like the original script is running successfully now.

**Comment by zjgarvey** [comment]
I'm going to mark this as closed, but feel free to reopen it if you are find issues with this op lowering.
