### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape' when trying to torch.compile nanoGPT model 

### ISSUE THREAD

**Issue by yuanfz98** [nod-ai/SHARK-Turbine#206]
Hello community,

I am unable to export nanoGPT model (git@github.com:karpathy/nanoGPT.git) with torch.compile:

```
if compile:
    print("compiling the model... (takes a ~minute)")
    unoptimized_model = model
    model = torch.compile(model, backend="turbine_cpu") # requires PyTorch 2.0

/root/.venv/turbine/bin/python /workspace/hongjing/nanoGPT/train.py config/train_shakespeare_char.py
```

```
cd /workspace/hongjing/nanoGPT/ ; /usr/bin/env /root/.venv/turbine/bin/python /root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 43507 -- /workspace/hongjing/nanoGPT/train.py /workspace/hongjing/nanoGPT/config/train_shakespeare_char.py 
Overriding config with /workspace/hongjing/nanoGPT/config/train_shakespeare_char.py:
# train a miniature character-level shakespeare model
# good for debugging and playing on macbooks and such

out_dir = 'out-shakespeare-char'
eval_interval = 250 # keep frequent because we'll overfit
eval_iters = 200
log_interval = 10 # don't print too too often

# we expect to overfit on this small dataset, so only save when val improves
always_save_checkpoint = False

wandb_log = False # override via command line if you like
wandb_project = 'shakespeare-char'
wandb_run_name = 'mini-gpt'

dataset = 'shakespeare_char'
gradient_accumulation_steps = 1
batch_size = 64
block_size = 256 # context of up to 256 previous characters

# baby GPT model :)
n_layer = 6
n_head = 6
n_embd = 384
dropout = 0.2

learning_rate = 1e-3 # with baby networks can afford to go a bit higher
max_iters = 5000
lr_decay_iters = 5000 # make equal to max_iters usually
min_lr = 1e-4 # learning_rate / 10 usually
beta2 = 0.99 # make a bit bigger because number of tokens per iter is small

warmup_iters = 100 # not super necessary potentially

# on macbook also add
# device = 'cpu'  # run on cpu only
# compile = False # do not torch compile the model

tokens per iteration will be: 16,384
found vocab_size = 65 (inside data/shakespeare_char/meta.pkl)
Initializing a new model from scratch
number of parameters: 10.65M
num decayed parameter tensors: 26, with 10,740,096 parameters
num non-decayed parameter tensors: 13, with 4,992 parameters
using fused AdamW: True
X= tensor([[ 1, 58, 43,  ...,  1, 58, 56],
        [41, 46, 39,  ..., 39, 58,  1],
        [56, 42, 47,  ..., 54, 59, 56],
        ...,
        [52,  1, 58,  ..., 16, 10,  0],
        [61, 47, 52,  ...,  6,  1, 40],
        [58, 46,  1,  ..., 43, 56, 60]], device='cuda:0')
Y= tensor([[58, 43, 50,  ..., 58, 56, 59],
        [46, 39, 56,  ..., 58,  1, 46],
        [42, 47, 58,  ..., 59, 56, 47],
        ...,
        [ 1, 58, 46,  ..., 10,  0, 35],
        [47, 52, 42,  ...,  1, 40, 59],
        [46,  1, 39,  ..., 56, 60, 43]], device='cuda:0')
type(X)= <class 'torch.Tensor'>
type(Y)= <class 'torch.Tensor'>
compiling the model... (takes a ~minute)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/workspace/hongjing/nanoGPT/train.py", line 274, in <module>
    losses = estimate_loss()
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/hongjing/nanoGPT/train.py", line 234, in estimate_loss
    logits, loss = model(X, Y)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2162, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 857, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 957, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1024, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1009, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/__init__.py", line 1607, in __call__
    return self.compiler_fn(model_, inputs_, **self.kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3891, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3429, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2212, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2392, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/root/.venv/turbine/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1573, in aot_dispatch_base
    compiled_fw = compiler(fw_module, flat_args)
  File "/workspace/hongjing/SHARK-Turbine/python/shark_turbine/dynamo/backends/cpu.py", line 73, in _base_backend
    importer.import_graph_module(gm)
  File "/workspace/hongjing/SHARK-Turbine/python/shark_turbine/dynamo/importer.py", line 245, in import_graph_module
    self.import_stateless_graph(gm.graph)
  File "/workspace/hongjing/SHARK-Turbine/python/shark_turbine/dynamo/importer.py", line 266, in import_stateless_graph
    node_importer.import_nodes(g.nodes)
  File "/workspace/hongjing/SHARK-Turbine/python/shark_turbine/dynamo/importer.py", line 501, in import_nodes
    self._import_torch_op_overload(loc, node, target)
  File "/workspace/hongjing/SHARK-Turbine/python/shark_turbine/dynamo/importer.py", line 654, in _import_torch_op_overload
    result_types.append(self._cc.tensor_metadata_to_type(v))
  File "/workspace/hongjing/SHARK-Turbine/python/shark_turbine/dynamo/importer.py", line 385, in tensor_metadata_to_type
    item.node if is_symbolic(item) else item for item in list(tm.shape)
torch._dynamo.exc.BackendCompilerFailed: backend='turbine_cpu' raised:
AttributeError: 'NoneType' object has no attribute 'shape'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

nanobind: leaked 64 instances!
nanobind: leaked 14 types!
 - leaked type "iree._runtime_libs._runtime.VmVariantList"
 - leaked type "iree._runtime_libs._runtime.HalBufferView"
 - leaked type "iree._runtime_libs._runtime.HalFence"
 - leaked type "iree._runtime_libs._runtime.HalBuffer"
 - leaked type "iree._runtime_libs._runtime.BufferUsage"
 - leaked type "iree._runtime_libs._runtime.VmContext"
 - leaked type "iree._runtime_libs._runtime.MappedMemory"
 - leaked type "iree._runtime_libs._runtime.HalElementType"
 - leaked type "iree._runtime_libs._runtime.VmInstance"
 - leaked type "iree._runtime_libs._runtime.VmModule"
 - leaked type "iree._runtime_libs._runtime.HalDevice"
 - ... skipped remainder
nanobind: leaked 88 functions!
 - leaked function ""
 - leaked function "push_int"
 - leaked function "map_to_dtype"
 - leaked function "lookup_function"
 - leaked function ""
 - leaked function "fill_zero"
 - leaked function "create_device"
 - leaked function "__eq__"
 - leaked function "create_default_device"
 - leaked function ""
 - leaked function "__iree_vm_cast__"
 - ... skipped remainder
nanobind: this is likely caused by a reference counting issue in the binding code.
```

Also dumped variables: 
![image](https://github.com/nod-ai/SHARK-Turbine/assets/42092999/69cd8c00-baf9-4acb-bfa9-eda511e7c45b)

I appreciate your help.

**Comment by vivekkhandelwal1** [comment]
Hi @yuanfz98, can you please confirm if this issue is still required or not?
