### ISSUE TITLE
LLAMA 2 Inference

### ISSUE THREAD

**Issue by alexsifivetw** [nod-ai/SHARK-Turbine#207]
Could any one run the LLAMA2 example using this [flow](https://github.com/nod-ai/SHARK-Turbine/tree/main/examples/llama2_inference) successfully?
I cannot find the `examples/llama2_inference/stateless_llama.py`.

https://github.com/nod-ai/SHARK-Turbine/tree/main/examples/llama2_inference

**Comment by alexsifivetw** [comment]
@IanNod Thanks! But I still encounter some issue when using the [script](https://github.com/nod-ai/SHARK-Turbine/blob/main/python/turbine_models/custom_models/stateless_llama.py).

```
/usr/local/lib/python3.11/dist-packages/transformers/models/auto/auto_factory.py:472: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [01:35<01:35, 95.99s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [02:21<00:00, 66.22s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [02:21<00:00, 70.79s/it]
/usr/local/lib/python3.11/dist-packages/transformers/utils/hub.py:374: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/auto/tokenization_auto.py:671: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
[2023-11-29 02:55:43,989] torch.fx.experimental.symbolic_shapes: [INFO] create_env
[2023-11-29 02:55:43,991] torch.fx.experimental.symbolic_shapes: [INFO] create_symbol s0 = 2 for input0.size()[1]
/usr/local/lib/python3.11/dist-packages/torch/overrides.py:110: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
/usr/local/lib/python3.11/dist-packages/torch/overrides.py:111: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
/usr/local/lib/python3.11/dist-packages/torch/overrides.py:117: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
/usr/local/lib/python3.11/dist-packages/torch/overrides.py:118: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
[2023-11-29 02:55:44,365] torch.fx.experimental.symbolic_shapes: [INFO] eval s0 <= 4096 [guard added] (transformers/models/llama/modeling_llama.py:140 in forward)
[2023-11-29 02:55:52,435] [0/0] torch.fx.experimental.symbolic_shapes: [INFO] create_env
[2023-11-29 02:55:53,133] [0/0] torch.fx.experimental.symbolic_shapes: [INFO] create_symbol s0 = 2 for L['arg0_1'].size()[1]
[2023-11-29 02:56:10,171] [0/0] torch.fx.experimental.symbolic_shapes: [INFO] produce_guards
[2023-11-29 02:56:23,417] torch.fx.experimental.symbolic_shapes: [INFO] create_env
[2023-11-29 02:56:23,418] torch.fx.experimental.symbolic_shapes: [INFO] create_symbol s0 = 2 for input1.size()[1]
[2023-11-29 02:56:23,418] torch.fx.experimental.symbolic_shapes: [INFO] create_symbol s1 = 32 for input1.size()[2]
[2023-11-29 02:56:23,420] torch.fx.experimental.symbolic_shapes: [INFO] create_symbol s2 = 128 for input1.size()[3]
[2023-11-29 02:56:24,485] torch.fx.experimental.symbolic_shapes: [INFO] eval s0 + 1 <= 4096 [guard added] (transformers/models/llama/modeling_llama.py:140 in forward)
[2023-11-29 02:56:24,511] torch.fx.experimental.symbolic_shapes: [INFO] eval Eq(s1, 32) [guard added] (_prims/__init__.py:1873 in _cat_meta)
[2023-11-29 02:56:24,514] torch.fx.experimental.symbolic_shapes: [INFO] eval Eq(s2, 128) [guard added] (_prims/__init__.py:1873 in _cat_meta)
[2023-11-29 02:56:29,469] [1/0] torch.fx.experimental.symbolic_shapes: [INFO] create_env
[2023-11-29 02:56:29,491] [1/0] torch.fx.experimental.symbolic_shapes: [INFO] create_symbol s0 = 2 for L['arg1_1'].size()[1]
[2023-11-29 02:56:29,495] [1/0] torch.fx.experimental.symbolic_shapes: [INFO] create_symbol s1 = 2 for L['arg2_1'].size()[1]
[2023-11-29 02:56:29,499] [1/0] torch.fx.experimental.symbolic_shapes: [INFO] create_symbol s2 = 2 for L['arg3_1'].size()[1]

... similar logs

[2023-11-29 02:56:44,832] [1/0] torch.fx.experimental.symbolic_shapes: [INFO] eval Eq(s63 + 1, s62 + 1) [guard added] at <eval_with_key>.5 from /usr/local/lib/python3.11/dist-packages/torch/fx/experimental/proxy_tensor.py:477 in wrapped:3367 in forward (_meta_registrations.py:3515 in common_meta_baddbmm_bmm)
[2023-11-29 02:56:48,920] [1/0] torch.fx.experimental.symbolic_shapes: [INFO] produce_guards
Traceback (most recent call last):
  File "/home/llama2/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 335, in <module>
    mod_str, _ = export_transformer_model(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llama2/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 238, in export_transformer_model
    flatbuffer_blob = ireec.compile_str(
                      ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/iree/compiler/tools/core.py", line 299, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/iree/compiler/tools/binaries.py", line 198, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Error code: -11
Diagnostics:

Invoked with:
 iree-compile /usr/local/lib/python3.11/dist-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=auto --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-embedded-linker-path=/usr/local/lib/python3.11/dist-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-input-type=torch --iree-vm-bytecode-module-output-format=flatbuffer-binary --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-target-triple=x86_64-linux-gnu --iree-llvmcpu-enable-microkernels --iree-llvmcpu-stack-allocation-limit=256000 --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-opt-const-expr-hoisting=False

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
```

It seems like the IREE component within SHARK-Turbine is not compatible.

**Comment by stellaraccident** [comment]
Can you please run `iree-compile --version` from the command line. Would like to know if the compiler is working at all.

**Comment by alexsifivetw** [comment]
@stellaraccident 
No any reaction.
I confirm that I installed them using `pip3.11 list`. Should I install them independently? Could it be a conflict with the `shark-turbine` package?
```
/home/llama2/SHARK-Turbine/python/turbine_models/custom_models# pip3.11 list | grep iree
iree-compiler            20231113.707
iree-runtime             20231113.707
```

**Comment by alexsifivetw** [comment]
BTW, I create a `vmfb` file (`llama2_torch.vmfb`) using the [script](https://github.com/nod-ai/SHARK-Turbine/blob/main/examples/llama2_inference/llama2.ipynb) successfully and try to use it.

```
python3.11 stateless_llama.py --run_vmfb --vmfb_path llama2_torch.vmfb
```

But I encounter:
```
Traceback (most recent call last):
  File "/home/llama2/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 333, in <module>
    run_vmfb_comparison(args)
  File "/home/llama2/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 275, in run_vmfb_comparison
    ctx = ireert.SystemContext(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/iree/runtime/system_api.py", line 208, in __init__
    self._vm_context = _binding.VmContext(
                       ^^^^^^^^^^^^^^^^^^^
ValueError: Error creating vm context with modules: c/runtime/src/iree/vm/context.c:156: NOT_FOUND; required module 'io_parameters' not registered on the context; resolving module 'state_update' imports
```

**Comment by stellaraccident** [comment]
Those are the current released versions.

When your say no response, you mean it doesn't print anything? Is there an exit code? (`echo $?`)

This does look like something environmental. Which os are you using?

**Comment by stellaraccident** [comment]
Those are the current released versions.

When your say no response, you mean it doesn't print anything? Is there an exit code? (`echo $?`)

This does look like something environmental. Which os are you using?

**Comment by stellaraccident** [comment]
This is a pretty basic failure: that is just a python wrapper script that calls a native executable. When if there is something wrong on the native side, it should dump a python stack trace unless if something low level is very screwed up.

**Comment by stellaraccident** [comment]
> BTW, I create a `vmfb` file (`llama2_torch.vmfb`) using the [script](https://github.com/nod-ai/SHARK-Turbine/blob/main/examples/llama2_inference/llama2.ipynb) successfully and try to use it.
> 
> ```
> python3.11 stateless_llama.py --run_vmfb --vmfb_path llama2_torch.vmfb
> ```
> 
> But I encounter:
> 
> ```
> Traceback (most recent call last):
>   File "/home/llama2/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 333, in <module>
>     run_vmfb_comparison(args)
>   File "/home/llama2/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 275, in run_vmfb_comparison
>     ctx = ireert.SystemContext(
>           ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/iree/runtime/system_api.py", line 208, in __init__
>     self._vm_context = _binding.VmContext(
>                        ^^^^^^^^^^^^^^^^^^^
> ValueError: Error creating vm context with modules: c/runtime/src/iree/vm/context.c:156: NOT_FOUND; required module 'io_parameters' not registered on the context; resolving module 'state_update' imports
> ```

There has to be a version mismatch at play. Pypi versions mixed with a local checkout at head or something. That doesn't explain the native failure.

I do note that you are using system python instead of a venv. That is pretty unrecommended. Among other things, it makes it really hard to know you are starting from a good state that is clean of conflicts.

**Comment by alexsifivetw** [comment]
I do it inside a podman container, so I don't use the python venv and follow the steps to install the dependencies:
```
podman run --name llama2 --platform linux/amd64 -v ./llama2:/home/llama2 -it ubuntu:22.04 bash
```

```
apt update && apt install -y curl git vim python3.11

# install pip for python3.11
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.11 get-pip.py

pip3.11 install shark-turbine
pip3.11 install transformers
pip3.11 install sentencepiece
pip3.11 install protobuf
```

Env:
- ubuntu:22.04
- Python3.11

**Comment by stellaraccident** [comment]
But your error messages show that you are mixing a local git checkout of SHARK-Turbine with the official PyPI release. The repo has moved forward at head and if you are trying to run scripts from it, they will depend on features that were not released in the official wheels. If you intend to be at HEAD for SHARK-Turbine, you need to follow instructions for developers: https://github.com/nod-ai/SHARK-Turbine#developers .

**Comment by alexsifivetw** [comment]
I follow the steps:
```
pip3.11 install --upgrade -r requirements.txt
pip3.11 install --upgrade -e .[torch-cpu-nightly,testing]
```

Use `pytest`:
```
...
=========================== short test summary info ============================
FAILED tests/dynamo/backend_smoke_test.py::test_basic - torch._dynamo.exc.Bac...
FAILED tests/dynamo/importer_basic_test.py::ImportTests::test_model_no_bias
FAILED tests/dynamo/importer_basic_test.py::ImportTests::test_model_with_bias
FAILED tests/dynamo/llama_test.py::ModelTests::testLLama - torch._dynamo.exc....
FAILED tests/dynamo/mninst_test.py::ModelTests::testMNISTEagerSimple - torch....
FAILED tests/dynamo/tensor_test.py::TensorTest::test_binary_op - ValueError: ...
FAILED tests/dynamo/tensor_test.py::TensorTest::test_nn_MLP - ValueError: fai...
FAILED tests/dynamo/tensor_test.py::TensorTest::test_nn_linear - ValueError: ...
FAILED tests/dynamo/tensor_test.py::TensorTest::test_unary_op - ValueError: f...
===== 9 failed, 1239 passed, 1 skipped, 259 xfailed, 35 warnings in 27.89s =====
```

Use `iree-compile`:
```
/usr/local/lib/python3.11/dist-packages/iree/compiler/tools/../_mlir_libs/iree-compile --version
Segmentation fault
```

**Comment by stellaraccident** [comment]
This is a very low level failure that has to be related to the specific system, container, etc. can you please reconfirm the container and a pip freeze with the exact iree-compile version?

The next step is to run that under gdb and try to determine the issue. This is the first time we've seen this kind of compatibility issue.

**Comment by alexsifivetw** [comment]
Thanks, I got a working `iree-compile` on Windows within a Docker container.
I tried running the script on my PC, which has 64GB RAM, but the process was killed.
```
python3.11 stateless_llama.py --compile_to vmfb --hf_auth_token <my_token>
```
How many RAM is needed to run the script successfully?

**Comment by stellaraccident** [comment]
> Thanks, I got a working `iree-compile` on Windows within a Docker container. I tried running the script on my PC, which has 64GB RAM, but the process was killed.
> 
> ```
> python3.11 stateless_llama.py --compile_to vmfb --hf_auth_token <my_token>
> ```
> 
> How many RAM is needed to run the script successfully?

@IanNod did some profiling lately. For the smallest of these models, the weights alone are ~28gb, and currently we were seeing that torch allocates about 2x that while processing the model. It seems like we should be able to avoid half of that but the allocations are in torch and we haven't dug into it more yet. In general, though, memory needed to process the model and weights scales with the size of the model. After the export phase, the needed memory is pretty bounded/small.

It is possible that, at the expense of some swapping, you could get by with just adding swap space.

**Comment by IanNod** [comment]
> Thanks, I got a working `iree-compile` on Windows within a Docker container. I tried running the script on my PC, which has 64GB RAM, but the process was killed.
> 
> ```
> python3.11 stateless_llama.py --compile_to vmfb --hf_auth_token <my_token>
> ```
> 
> How many RAM is needed to run the script successfully?

To run the default settings I think you need something like 128GB. We have added support for essentially stripping the weights and providing them as external parameters which reduces memory needed by quite a bit. You can enable with this flag --external_weights=safetensors. With that you might be able to get away with 32 GB RAM to compile that vmfb.

You can save those weights either with this script https://github.com/nod-ai/SHARK-Turbine/blob/main/python/turbine_models/gen_external_params/gen_external_params.py (if you use quantized weights this is necessary) or without quantization you can add the flag --external_weight_file=<path to where you want to save them>

**Comment by stellaraccident** [comment]
Ah, thanks my comments were related to using external weights.

**Comment by alexsifivetw** [comment]
Thanks! I did it on my PC with the `--external_weights` and `--external_weight_file` options.
```
# Compile vmfb
python3.11 stateless_llama.py --compile_to=vmfb --external_weights=safetensors --external_weight_file=Llama_2_7b_chat_hf.safetensors --hf_auth_token=<my_token>

# Inference
python3.11 stateless_llama.py --run_vmfb --vmfb_path=Llama_2_7b_chat_hf.vmfb --external_weight_file=Llama_2_7b_chat_hf.safetensors --hf_auth_token=<my_token>
```

prompt: `Hi`

Output:
```
turbine output:
Hello! It's nice to meet you. Is there something I can help you with or would you like to chat?</s>

torch output:
Hello! It's nice to meet you. Is there something I can help you with or would you like to chat?</s>
```

**Comment by ElEHsiang** [comment]
Just want to take a note that related to this issue. I hit segmentation fault while running the `iree-compile` install by pip (iree-compiler==20240226.813). The kernel log shows 
```
[4323212.646870] 2431577 (iree-compile): Uhuuh, elf segment at 0000000000200000 requested but the memory is mapped already
```
The overlapped segmets are
```
  LOAD           0x0000000000001568 0x0000000000200568 0x0000000000200568
                 0x0000000000000180 0x0000000000000180  R      0x1000
  GNU_EH_FRAME   0x00000000000015f0 0x00000000002005f0 0x00000000002005f0
                 0x0000000000000034 0x0000000000000034  R      0x4
```
This might be the linux kernel problem. We use redhat8.7 which is based on linux kernel-4.18. The linux kernel-4.18 does not include this patch https://lore.kernel.org/lkml/202110051626.0AB43704@keescook/T/. So the problem can only be reproduce on our redhat but not ubuntu.

By the way, the iree-compiler==20240410.859 can run on redhat8.7. The overlapped segments are changed and these will not be forbid by kernel.
```
  INTERP         0x00000000000002a8 0x00000000002002a8 0x00000000002002a8
                 0x000000000000001c 0x000000000000001c  R      0x1
  GNU_EH_FRAME   0x0000000000000580 0x0000000000200580 0x0000000000200580
                 0x0000000000000034 0x0000000000000034  R      0x4

```

**Comment by stellaraccident** [comment]
> Just want to take a note that related to this issue. I hit segmentation fault while running the `iree-compile` install by pip (iree-compiler==20240226.813). The kernel log shows
> 
> ```
> [4323212.646870] 2431577 (iree-compile): Uhuuh, elf segment at 0000000000200000 requested but the memory is mapped already
> ```
> 
> The overlapped segmets are
> 
> ```
>   LOAD           0x0000000000001568 0x0000000000200568 0x0000000000200568
>                  0x0000000000000180 0x0000000000000180  R      0x1000
>   GNU_EH_FRAME   0x00000000000015f0 0x00000000002005f0 0x00000000002005f0
>                  0x0000000000000034 0x0000000000000034  R      0x4
> ```
> 
> This might be the linux kernel problem. We use redhat8.7 which is based on linux kernel-4.18. The linux kernel-4.18 does not include this patch https://lore.kernel.org/lkml/202110051626.0AB43704@keescook/T/. So the problem can only be reproduce on our redhat but not ubuntu.
> 
> By the way, the iree-compiler==20240410.859 can run on redhat8.7. The overlapped segments are changed and these will not be forbid by kernel.
> 
> ```
>   INTERP         0x00000000000002a8 0x00000000002002a8 0x00000000002002a8
>                  0x000000000000001c 0x000000000000001c  R      0x1
>   GNU_EH_FRAME   0x0000000000000580 0x0000000000200580 0x0000000000200580
>                  0x0000000000000034 0x0000000000000034  R      0x4
> ```

This seems like an issue that should be filed in the upstream iree project, although tbh, the mechanism is new to me and I don't have an idea on how to solve it (we build on an 8.x RH like, do this isn't even a cross Linux portability issue but a kernel bug).

I'm going to go ahead and close this issue as I can no longer even figure out how we are related to the original issue and subsequent investigation.
