### ISSUE TITLE
torch.onnx.export is not able to export a model of bfloat16 type

### ISSUE THREAD

**Issue by kumardeepakamd** [nod-ai/SHARK-Turbine#378]
**Issue**
If I get an opt torch model and to .to(bf16) and then call torch.onnx.export on it, it fails.

File it on PyTorch. Logged here to track.

**STR**
save following as model.py
```
import sys, argparse
import torch
from transformers import OPTModel, AutoTokenizer

test_model_name = "facebook/opt-1.3b"
model = OPTModel.from_pretrained(
    test_model_name,
    num_labels=2,
    output_attentions=False,
    output_hidden_states=False,
    torchscript=True,
)
model.eval()
tokenizer = AutoTokenizer.from_pretrained(test_model_name)
test_input = torch.tensor([tokenizer.encode("The test prommpt")])
test_output = model(test_input)[0]
print("Input:", test_input)
print("Output:", test_output)

model = model.to(torch.bfloat16)
test_input = test_input.to(torch.bfloat16)

onnx_name = "model.onnx"
onnx_program = torch.onnx.export(model, test_input, onnx_name, export_params=True)
```

And run:
```
python ./model.py
```

You get following error:
```
Traceback (most recent call last):
  File "/proj/gdba/kumar/nod/SHARK-TestSuite/e2eshark/test-run-bf16-onnx-2/pytorch/models/opt-1.3b/runmodel.py", line 109, in <module>
    onnx_program = torch.onnx.export(model, test_input, onnx_name, export_params=True)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/onnx/utils.py", line 1613, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/onnx/utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/onnx/utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/onnx/utils.py", line 915, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/jit/_trace.py", line 1296, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/jit/_trace.py", line 138, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/jit/_trace.py", line 129, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 996, in forward
    decoder_outputs = self.decoder(
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 831, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/proj/gdba/kumar/anaconda3/envs/e2e/lib/python3.10/site-packages/torch/nn/functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got CPUBFloat16Type instead (while checking arguments for embedding)


```

**Comment by kumardeepakamd** [comment]
Maybe model.to is not the right way to handle it. The Embedding address look up should stay as int. So, we need a way to convert those portions of the model and parameters to bfloat16 which are non-address related. Does such a thing exist? Or do we need to build one?

**Comment by kumardeepakamd** [comment]
@Shukla-Gaurav / @PhaneeshB , Maybe we should file an issue on PyTorch in addition to finding our own solution -- ONNX export and/or model.to should handle it. Want to do that and note a link to that here?

**Comment by kumardeepakamd** [comment]
By keeping input as int, we are able to get onnx file. @PhaneeshB got it to work. This can be closed.

**Comment by stellaraccident** [comment]
> @Shukla-Gaurav / @PhaneeshB , Maybe we should file an issue on PyTorch in addition to finding our own solution -- ONNX export and/or model.to should handle it. Want to do that and note a link to that here?

I've never worked in a modeling shop where the framework was expected to handle policy decisions like that... Making these decisions is a critical part of formulating the model for inference and can't be done generically. I think you're using a part with constrained arithmetic and just want a fairly aggressive conversion. But consider that most things that support bf16 can support other things and would make different, layer level tradeoffs.

I've typically seen this be implemented at the model level and controlled with hyper parameters.
