### ISSUE TITLE
Compile TinyLlama Failed

### ISSUE THREAD

**Issue by rednoah91** [nod-ai/SHARK-Turbine#458]
Hi, I'd like to run TinyLlama via SHARK-Turbine. When I execute:
```
 python python/turbine_models/custom_models/stateless_llama.py --compile_to=vmfb --external_weights="safetensors" --quantization="int4" --precision="f16" --hf_model_name="TinyLlama/TinyLlama-1.1B-Chat-v0.2"
```
I got the following errors:
```
Traceback (most recent call last):
  File "/home/hongrongh/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 384, in <module>
    mod_str, _ = export_transformer_model(
  File "/home/hongrongh/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 308, in export_transformer_model
    inst = StateUpdateModule(context=Context(), import_to=import_to)
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/compiled_module.py", line 552, in __new__
    do_export(proc_def)
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/compiled_module.py", line 549, in do_export
    trace.trace_py_func(invoke_with_self)
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/support/procedural/tracer.py", line 121, in trace_py_func
    return_py_value = _unproxy(py_f(*self.proxy_posargs, **self.proxy_kwargs))
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/compiled_module.py", line 530, in invoke_with_self
    return proc_def.callable(self, *args, **kwargs)
  File "/home/hongrongh/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 167, in run_initialize
    token, *state = self.initialize(x, constraints=init_const)
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/support/procedural/base.py", line 137, in __call__
    return current_ir_trace().handle_call(self, args, kwargs)
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/support/procedural/tracer.py", line 137, in handle_call
    return target.resolve_call(self, *args, **kwargs)
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/builtins/jittable.py", line 207, in resolve_call
    transformed_f = functorch_functionalize(transformed_f, *flat_pytorch_args)
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/passes/functorch.py", line 47, in functorch_functionalize
    new_gm = proxy_tensor.make_fx(
  File "/home/hongrongh/SHARK-Turbine/turbine_venv/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 809, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/home/hongrongh/SHARK-Turbine/turbine_venv/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/hongrongh/SHARK-Turbine/turbine_venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/hongrongh/SHARK-Turbine/turbine_venv/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/hongrongh/SHARK-Turbine/turbine_venv/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 468, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/home/hongrongh/SHARK-Turbine/turbine_venv/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
  File "/home/hongrongh/SHARK-Turbine/turbine_venv/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 485, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/passes/functorch.py", line 65, in wrapped
    out = function(*args_functional)
  File "/home/hongrongh/SHARK-Turbine/python/shark_turbine/aot/builtins/jittable.py", line 202, in flat_wrapped_f
    return self.wrapped_f(*pytorch_args, **pytorch_kwargs)
  File "/home/hongrongh/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 216, in initialize
    state1_flat = [torch.transpose(x, 1, 2) for x in state1_flat]
  File "/home/hongrongh/SHARK-Turbine/python/turbine_models/custom_models/stateless_llama.py", line 216, in <listcomp>
    state1_flat = [torch.transpose(x, 1, 2) for x in state1_flat]
TypeError: transpose() received an invalid combination of arguments - got (NoneType, int, int), but expected one of:
 * (Tensor input, int dim0, int dim1)
      didn't match because some of the arguments have invalid types: (NoneType, int, int)
 * (Tensor input, name dim0, name dim1)
      didn't match because some of the arguments have invalid types: (NoneType, int, int)
```
Have you ever encountered this? Does it make sense to compile TinyLlama by `stateless_llama.py`?

Thanks.

**Comment by stellaraccident** [comment]
Sometimes the wrapper script needs per model adaptation. It's all just conversation how these models are defined.

@IanNod I assume we haven't tried this one?

**Comment by rednoah91** [comment]
Kindly pinging here. Do you have a plan to support TinyLlama : )?

**Comment by IanNod** [comment]
I was able to generate TinyLlama/TinyLlama-1.1B-Chat-v1.0 relatively recently through stateless_llama.py. I believe there was a PR a little while back that fixed this case: https://github.com/nod-ai/SHARK-Turbine/commit/4c42076218c690c90ad07eb797c4e8f144606685 
@rednoah91 can you verify this error on the latest SHARK-Turbine version?

**Comment by rednoah91** [comment]
Thanks for your suggestion @IanNod. I can generate vmfb successfully with latest SHARK-Turbine. However, I encountered error when I running with llm_runner.py:
```
$ python models/turbine_models/custom_models/llm_runner.py --vmfb_path=./TinyLlama_1.1B_Chat_v1.0.vmfb --external_weight_path=./TinyLlama_1.1B_Chat_v1.0_f16_int4.safetensors --device=local-task
generating turbine output:
Traceback (most recent call last):
  File "/home/hongrongh/SHARK-Turbine/models/turbine_models/custom_models/llm_runner.py", line 249, in <module>
    turbine_output = run_llm(
  File "/home/hongrongh/SHARK-Turbine/models/turbine_models/custom_models/llm_runner.py", line 177, in run_llm
    llm = SharkLLM(
  File "/home/hongrongh/SHARK-Turbine/models/turbine_models/custom_models/llm_runner.py", line 91, in __init__
    self.runner = vmfbRunner(
  File "/home/hongrongh/SHARK-Turbine/models/turbine_models/model_runner.py", line 27, in __init__
    self.ctx = ireert.SystemContext(
  File "/home/hongrongh/SHARK-Turbine/turbine_venv/lib/python3.10/site-packages/iree/runtime/system_api.py", line 191, in __init__
    self._vm_context = _binding.VmContext(
IndexError: Error creating vm context with modules: c/runtime/src/iree/io/parameter_index_provider.c:211: OUT_OF_RANGE; parameter `model.embed_tokens.weight` range out of bounds (offset=0, length=262144000, size=131072000); while invoking native function io_parameters.load; while calling import;
[ 1]   native io_parameters.load:0 -
[ 0] bytecode state_update.__init:6624 [
    <stdin>:2:3,
    <stdin>:3:3,
    <stdin>:4:3,
    <stdin>:5:3,
...
```
Have you tried to run it?

**Comment by IanNod** [comment]
I did run it before. The only issue I recall having is the llm_runner.py inference prompt api doesn't match for tinyllama so I had to change that format. Basically the prompt portion like <s>[INST] <<SYS>> needs to be changed to match tinyllama or it will get stuck in a loop waiting for an EOS token.

The error you posted looks like a mismatch between the compiled vmfb expected precision/quantization and the provided external safetensor weights precision/quantization. Can you verify the vmfb was compiled for --precision=f16 and --quantization=int4 like it appears your safetensor weights were generated for?

**Comment by rednoah91** [comment]
Thanks for your reminder @IanNod. I can run TinyLlama successfully after:
1. specifying --precision=f16 and --quantization=int4 in stateless_llama.py to match the safetensors data-types.
2. Modify B_INST/E_INST to B_SYS/E_SYS in llm_runner.py:
```
diff --git a/models/turbine_models/custom_models/llm_runner.py b/models/turbine_models/custom_models/llm_runner.py
index 7c10800..030a11a 100644
--- a/models/turbine_models/custom_models/llm_runner.py
+++ b/models/turbine_models/custom_models/llm_runner.py
@@ -75,7 +75,7 @@ Be concise. You are a helpful, respectful and honest assistant. If a question do


 def append_user_prompt(history, input_prompt):
-    user_prompt = f"{B_INST} {input_prompt} {E_INST}"
+    user_prompt = f"{B_SYS} {input_prompt} {E_SYS}"
     history += user_prompt
     return history
```
I found the performance is only 3.07 tokens/s on my AMD Ryzen 9 3950X machine, which is far behind the performance of llama.cpp (48.12 tokens/s). Is that make sense? Did I miss adding any flags/compiler options?

**Comment by stellaraccident** [comment]
@Max191 may have a stash of flags, but to set expectations, we're heads down in another workload for the next bit and won't be able to try many things.

One thing: f16 on x86 CPUs has been trouble for us as they typically only have hardware support for conversion. On those targets, we almost always use a hybrid strategy with f32 computation against lower precession weights. None of IREE's f16 arithmetic is optimized on f16/x86, and it has a tendency to do exactly what it is told on that front, even if slow.

There may be other things, but that's a big one iirc.

**Comment by rednoah91** [comment]
Got it. Thanks for your reply @stellaraccident

**Comment by Max191** [comment]
> I found the performance is only 3.07 tokens/s on my AMD Ryzen 9 3950X machine, which is far behind the performance of llama.cpp (48.12 tokens/s). Is that make sense? Did I miss adding any flags/compiler options?

As Stella mentioned, one factor here would be that `f16` is not supported very well on x86 CPUs. I do have some IREE flags that can help with the quantized portion of the workload, but it is still experimental. The experimental work should carry into other models like TinyLlama, but for now we need to flesh out the path for Llama7B first.
