### ISSUE TITLE
Pip install pulls in numpy 2.0 incompatible with iree-runtime package

### ISSUE THREAD

**Issue by ScottTodd** [nod-ai/SHARK-Turbine#530]
Platform: Windows, Python 3.11.

After `pip install -e core -r core\requirements.txt` , I get this error:

```bash
λ python
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from iree import runtime as ireert

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0b1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled against NumPy 2.0.

If you are a user of the module, the easiest solution will be to
either downgrade NumPy or update the failing module (if available).

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "D:\dev\projects\SHARK-Turbine\main.venv\Lib\site-packages\iree\runtime\__init__.py", line 13, in <module>
    from . import _binding
  File "D:\dev\projects\SHARK-Turbine\main.venv\Lib\site-packages\iree\runtime\_binding.py", line 19, in <module>
    from .._runtime.libs import _runtime
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\dev\projects\SHARK-Turbine\main.venv\Lib\site-packages\iree\runtime\__init__.py", line 13, in <module>
    from . import _binding
  File "D:\dev\projects\SHARK-Turbine\main.venv\Lib\site-packages\iree\runtime\_binding.py", line 19, in <module>
    from .._runtime.libs import _runtime
ImportError: numpy.core.multiarray failed to import
```

Install logs:
```
λ pip install -e core -r core\requirements.txt
Looking in links: https://openxla.github.io/iree/pip-release-links.html
Obtaining file:///D:/dev/projects/SHARK-Turbine/core
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting torch==2.1.0
  Downloading torch-2.1.0-cp311-cp311-win_amd64.whl (192.3 MB)
     ---------------------------------------- 192.3/192.3 MB 9.6 MB/s eta 0:00:00
Collecting mpmath==1.3.0
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting torchvision
  Using cached torchvision-0.17.1-cp311-cp311-win_amd64.whl (1.2 MB)
Collecting iree-compiler==20240311.828
  Downloading https://github.com/openxla/iree/releases/download/candidate-20240311.828/iree_compiler-20240311.828-cp311-cp311-win_amd64.whl (45.0 MB)
     ---------------------------------------- 45.0/45.0 MB 46.7 MB/s eta 0:00:00
Collecting iree-runtime==20240311.828
  Downloading https://github.com/openxla/iree/releases/download/candidate-20240311.828/iree_runtime-20240311.828-cp311-cp311-win_amd64.whl (4.1 MB)
     ---------------------------------------- 4.1/4.1 MB 64.5 MB/s eta 0:00:00
Collecting filelock
  Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx
  Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Collecting jinja2
  Using cached Jinja2-3.1.3-py3-none-any.whl (133 kB)
Collecting fsspec
  Using cached fsspec-2024.2.0-py3-none-any.whl (170 kB)
Collecting numpy
  Using cached numpy-2.0.0b1-cp311-cp311-win_amd64.whl (16.5 MB)
Collecting PyYAML
  Using cached PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
Collecting torchvision
  Downloading torchvision-0.17.0-cp311-cp311-win_amd64.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 72.3 MB/s eta 0:00:00
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting torchvision
  Downloading torchvision-0.16.2-cp311-cp311-win_amd64.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 70.5 MB/s eta 0:00:00
  Downloading torchvision-0.16.1-cp311-cp311-win_amd64.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB ? eta 0:00:00
  Downloading torchvision-0.16.0-cp311-cp311-win_amd64.whl (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 78.3 MB/s eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0
  Using cached pillow-10.2.0-cp311-cp311-win_amd64.whl (2.6 MB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl (17 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Building wheels for collected packages: shark-turbine
  Building editable for shark-turbine (pyproject.toml) ... done
  Created wheel for shark-turbine: filename=shark_turbine-0.9.7.dev1-0.editable-py3-none-any.whl size=5774 sha256=0a62b8e48f48385fa766eff95ca044dc13cb844145e24b6c87157aaa64414094
  Stored in directory: C:\Users\Scott\AppData\Local\Temp\pip-ephem-wheel-cache-_qotudbq\wheels\f9\05\14\0b91dedac55ce4ea23840565f54ed3ae31a195cc020af67c33
Successfully built shark-turbine
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, PyYAML, pillow, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, iree-runtime, iree-compiler, torch, torchvision, shark-turbine
Successfully installed MarkupSafe-2.1.5 PyYAML-6.0.1 certifi-2024.2.2 charset-normalizer-3.3.2 filelock-3.13.1 fsspec-2024.2.0 idna-3.6 iree-compiler-20240311.828 iree-runtime-20240311.828 jinja2-3.1.3 mpmath-1.3.0 networkx-3.2.1 numpy-2.0.0b1 pillow-10.2.0 requests-2.31.0 shark-turbine-0.9.7.dev1 sympy-1.12 torch-2.1.0 torchvision-0.16.0 typing-extensions-4.10.0 urllib3-2.2.1

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
```

I think this is coming from `--pre` in https://github.com/nod-ai/SHARK-Turbine/blob/1cccf4dd8c635159155f754fab17947c81b91cab/core/pytorch-cpu-requirements.txt#L1-L2 since numpy 2.0+ is still marked as pre-release: https://pypi.org/project/numpy/#history (new as of recently / several days ago?)

**Comment by ScottTodd** [comment]
Potential workaround: `pip install --force-reinstall -v "numpy==1.26.4"`

**Comment by stellaraccident** [comment]
We can upgrade iree. Can you?

**Comment by ScottTodd** [comment]
IREE is pinned to `numpy>=1.19.4` right now: https://github.com/openxla/iree/blob/main/runtime/bindings/python/iree/runtime/build_requirements.txt

Could try opting in to the prerelease there and testing if it's backwards compatible. I'm not sure how that would work across multiple projects - would everyone using these packages then also need to update to numpy's prerelease 2.0?

**Comment by ScottTodd** [comment]
https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice ah. Nice.

> When you build wheels for your package using a NumPy 2.x version at build time, those will work with NumPy 1.xx.

**Comment by ScottTodd** [comment]
Yeah, I can work on that once I flush a few more things from my queue.
