### ISSUE TITLE
F.grid_sample through turbine on IREE compilation

### ISSUE THREAD

**Issue by harishanand95** [nod-ai/SHARK-Turbine#542]
`F.grid_sample` fails at IREE compilation. How to fix this error? Thanks!

#### Versions
```bash
shark-turbine            0.9.7.dev1
iree-compiler            20240311.828
iree-runtime             20240311.828
torch                    2.4.0.dev20240320+cpu
```
#### Code
```python
import torch
import torch.nn.functional as F
from iree.compiler.extras.fx_importer import FxImporter
import iree.compiler as ireec


class GS(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x, indices2D):
        out = F.grid_sample(x, indices2D, align_corners=False, mode="bilinear")
        return out

def compile_to_vmfb(module_str, device, target_triple, max_alloc, safe_name):
    flags = [
        "--iree-input-type=torch",
        "--mlir-print-debuginfo",
        "--mlir-print-op-on-diagnostic=false",
        "--iree-llvmcpu-target-cpu-features=host",
        "--iree-llvmcpu-target-triple=x86_64-linux-gnu",
        "--iree-stream-resource-index-bits=64",
        "--iree-vm-target-index-bits=64",
        "--iree-flow-inline-constants-max-byte-length=1",
    ]
    if device == "cpu":
        flags.append("--iree-llvmcpu-enable-ukernels=all")
        device = "llvm-cpu"
    elif device == "vulkan-spirv": # FIX in SHARK-Turbine
        flags.extend(
            [
                "--iree-hal-target-backends=vulkan-spirv",
                "--iree-vulkan-target-triple=" + target_triple,
                "--iree-stream-resource-max-allocation-size=" + max_alloc,
            ]
        )
    elif device == "rocm":
        flags.extend(
            [
                "--iree-hal-target-backends=rocm",
                "--iree-rocm-target-chip=" + target_triple,
                "--iree-rocm-link-bc=true",
                "--iree-rocm-bc-dir=/opt/rocm/amdgcn/bitcode",
                "--iree-vm-bytecode-module-strip-source-map=true",
                "--iree-opt-strip-assertions=true",
                "--iree-vm-target-truncate-unsupported-floats",
            ]
        )
    elif device == "cuda":
        flags.extend(
            [
                "--iree-hal-target-backends=cuda",
                "--iree-hal-cuda-llvm-target-arch=" + target_triple,
                "--iree-vm-bytecode-module-strip-source-map=true",
                "--iree-vm-target-truncate-unsupported-floats",
            ]
        )
    else:
        print("incorrect device: ", device)

    flatbuffer_blob = ireec.compile_str(
        module_str,
        target_backends=[device],
        extra_args=flags,
    )
    with open(f"{safe_name}.vmfb", "wb+") as f:
        f.write(flatbuffer_blob)
    print("Saved to", safe_name + ".vmfb")


def render_export(device="cpu", target_triple="", max_alloc="4294967296"):
    # my values
    x = torch.ones(3, 40, 64, 64, dtype=torch.float32)
    indices = torch.ones(3, 1, 8192, 2, dtype=torch.float32)

    # torch-mlir test values 
    x = torch.rand(1, 1, 4, 4, dtype=torch.float32)
    indices = torch.rand(1, 1, 3, 2, dtype=torch.float32)

    model = GS()
    y = model(x, indices)
    
    prog = torch.export.export(model, args=(x, indices))
    importer = FxImporter()
    importer.import_frozen_program(prog)

    output_file = "gs.mlir"
    print("Saving to:", output_file)
    with open(output_file, "w") as f:
        importer.module_op.print(file=f, binary=False)

    module_str = str(importer.module_op)
    compile_to_vmfb(module_str, device, target_triple, max_alloc, "gs")

render_export()
# render_export(device="vulkan-spirv", target_triple="ampere-rtx4070-linux", max_alloc="4294967296")
```
#### Error
```bash
Saving to: gs.mlir
Traceback (most recent call last):
  File "/home/harish/projects/turbine/turbine-lrm/turbine/grid_sampler2d.py", line 96, in <module>
    render_export()
  File "/home/harish/projects/turbine/turbine-lrm/turbine/grid_sampler2d.py", line 94, in render_export
    compile_to_vmfb(module_str, device, target_triple, max_alloc, "gs")
  File "/home/harish/projects/turbine/turbine-lrm/turbine/grid_sampler2d.py", line 62, in compile_to_vmfb
    flatbuffer_blob = ireec.compile_str(
                      ^^^^^^^^^^^^^^^^^^
  File "/home/harish/venvs/head_turbine/lib/python3.11/site-packages/iree/compiler/tools/core.py", line 299, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harish/venvs/head_turbine/lib/python3.11/site-packages/iree/compiler/tools/binaries.py", line 198, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Error code: 1
Diagnostics:
<stdin>:6:10: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %0 = torch.operator "torch.aten.grid_sampler_2d"(%arg0, %arg1, %int0, %int0_0, %false) : (!torch.vtensor<[1,1,4,4],f32>, !torch.vtensor<[1,1,3,2],f32>, !torch.int, !torch.int, !torch.bool) -> !torch.vtensor<[1,1,1,3],f32> 
         ^


Invoked with:
 iree-compile /home/harish/venvs/head_turbine/lib/python3.11/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=auto --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-embedded-linker-path=/home/harish/venvs/head_turbine/lib/python3.11/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-input-type=torch --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-target-triple=x86_64-linux-gnu --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-flow-inline-constants-max-byte-length=1 --iree-llvmcpu-enable-ukernels=all

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
```
#### MLIR 
```MLIR
module {
  func.func @main(%arg0: !torch.vtensor<[1,1,4,4],f32>, %arg1: !torch.vtensor<[1,1,3,2],f32>) -> !torch.vtensor<[1,1,1,3],f32> {
    %int0 = torch.constant.int 0
    %int0_0 = torch.constant.int 0
    %false = torch.constant.bool false
    %0 = torch.operator "torch.aten.grid_sampler_2d"(%arg0, %arg1, %int0, %int0_0, %false) : (!torch.vtensor<[1,1,4,4],f32>, !torch.vtensor<[1,1,3,2],f32>, !torch.int, !torch.int, !torch.bool) -> !torch.vtensor<[1,1,1,3],f32> 
    return %0 : !torch.vtensor<[1,1,1,3],f32>
  }
}

```

**Comment by ScottTodd** [comment]
I see GridSample lowered from ONNX to Torch with https://github.com/nod-ai/SHARK-Turbine/issues/363, but these e2e ONNX tests in IREE are  failing to compile:
```
test_gridsample
test_gridsample_aligncorners_true
test_gridsample_bicubic
test_gridsample_bicubic_align_corners_0_additional_1
test_gridsample_bicubic_align_corners_1_additional_1
test_gridsample_bilinear
test_gridsample_bilinear_align_corners_0_additional_1
test_gridsample_bilinear_align_corners_1_additional_1
test_gridsample_border_padding
test_gridsample_nearest
test_gridsample_nearest_align_corners_0_additional_1
test_gridsample_nearest_align_corners_1_additional_1
test_gridsample_reflection_padding
test_gridsample_volumetric_bilinear_align_corners_0
test_gridsample_volumetric_bilinear_align_corners_1
test_gridsample_volumetric_nearest_align_corners_0
test_gridsample_volumetric_nearest_align_corners_1
test_gridsample_zeros_padding
```

Might be missing a lowering to linalg.

**Comment by ScottTodd** [comment]
cc @afalkenberg1

**Comment by rsuderman** [comment]
So this appears to be `grid_sampler_2d`. Its possible we can just reroute the operation into the existing `grid_sampler` lowering. Often these cases are more op-explosion with a single workable operation.

**Comment by afalkenberg1** [comment]
The grid_sampler implementation does not cover all cases that is correct. The onnx->torch lowering generates the appropriate messages for the cases which are not working (yet). I need to add the other cases.
